# Utilise une image Python officielle
FROM python:3.9-slim

# Installe les dépendances système nécessaires pour pandas et openpyxl
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    python3-dev \
    libpq-dev && \
    rm -rf /var/lib/apt/lists/*

# Définir le répertoire de travail
WORKDIR /app

# Copier les dépendances Python et les installer
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste du projet
COPY . .

# Créer les dossiers pour les uploads et outputs
RUN mkdir -p /app/data/uploads && mkdir -p /app/data/output

# Lancer l'application FastAPI
CMD ["uvicorn", "render_app:app", "--host", "0.0.0.0", "--port", "8000"]
