# Utilise une image Python légère et officielle
FROM python:3.9-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les dépendances et les installer
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste du projet
COPY . .

# Créer les dossiers pour les uploads et outputs
RUN mkdir -p /app/data/uploads && mkdir -p /app/data/output

# Lancer l'application FastAPI
CMD ["uvicorn", "render_app:app", "--host", "0.0.0.0", "--port", "8000"]
